- server/db/models/index.js
- server/db/models/product.js
@PhurbaSherpa @sam049 @Jordan1C 
* Added Product to the models file in the db
* Additionally imported the Product model to the index.js file within the models folder
> Added Product model

- script/seed.js
@cgerace @PhurbaSherpa @Jordan1C 
Made a test seed file
> Seed file 

- server/db/models/user.js
updated existing user model to agreed upon specifications from group
> finally got add to work

- server/api/index.js
- server/api/products.js
- server/api/users.js
> basic-routes

- client/store/index.js
- client/store/product.js
- client/store/user.js
Product reducer done minus thunks for non-existent api routes (add, delete, update)
User reducer updated to match syntax and naming conventions with product reducer
> user and product reducers

- package.json
- script/seed.js
- server/db/models/category.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/orderProduct.js
- server/db/models/product.js
Added new models: Category, Order, OrderProducts
Updated Seed file to have date for all of our tables.
@PhurbaSherpa @Jordan1C @sam049
> Updated and Added models and associations, updated Seed

- client/components/AllProducts.js
- client/components/SingleProduct.js
- client/components/navbar.js
- client/components/user-home.js
- client/routes.js
- client/store/product.js
- public/index.html
- server/api/products.js
- server/auth/google.js
> allProducts page and singlePageProduct

- server/api/products.js
> product api routes

- client/store/cart.js
- server/api/cart.js
- server/api/index.js
check out these routes, theyre awesome!
> cart routes

- client/components/CartItem.js
- client/components/ShoppingCart.js
- client/components/navbar.js
- client/routes.js
- client/store/cart.js
- client/store/product.js
- server/api/cart.js
- server/api/index.js
- server/api/order.js
- server/db/models/order.js
cart checkout route and shopping cart components
> Cartfrontend

- client/components/ShoppingCart.js
- script/seed.js
- server/db/models/order.js
- server/db/models/user.js
- Initialized an active Order for each new user (using User.afterCreate)
- Had to update the seed file because of the above, so we could still have helpful test data
- Removed the creditCard field from the Order model
- For the Order.getActiveOrder function on the Order model, brought in some attributes from the Product model so would display on /cart
> Add product name to cart

- client/components/ShoppingCart.js
- client/components/SingleProduct.js
- server/api/cart.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
> atc feature added

- client/components/OrderDetail.js
- client/components/ShoppingCart.js
- client/components/SingleProduct.js
- client/routes.js
- server/api/cart.js
- server/api/order.js
- server/auth/index.js
Sam and I created an order detail page component
> Order Detail Page

- client/store/index.js
- client/store/order.js
- client/store/product.js
- server/api/order.js
- added try catches to remaining thunks
- added order apis that sam and I made on friday
- created order reducer for aforementioned apis, not yet hooked up due to postgres issues
- did a look over of the code to remove any remaining console logs (there werent any)
> code cleanup and order api prep

- client/components/OrderDetail.js
- client/store/user.spec.js
- server/api/users.js
- server/api/users.spec.js
- server/db/models/order.js
- server/db/models/user.js
- server/index.js
Just ran through and added some missing try-catches
> Added Try Catches

- client/components/OrderDetail.js
- server/api/cart.js
order detail page is now reduxed, and now (kinda) prints shipping address
> thunked checkout page

- client/app.js
- client/components/AllCategories.js
- client/components/AllProducts.js
- client/components/Deals.js
- client/components/SingleProduct.js
- client/components/footer.js
- client/components/index.js
- client/components/navbar.js
- client/components/user-home.js
- client/store/product.js
- public/index.html
- public/style.css
- server/api/cart.js
- server/db/models/product.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
> home page css

- script/seed.js
- server/api/products.js
- server/api/users.js
- server/db/models/user.js
- Added middleware func called isAdmin() to routes which should only be available to admins
> Adding admin access

- client/components/Order.js
- client/components/OrderDetail.js
- client/components/OrderHistory.js
- client/components/ShoppingCart.js
- client/components/navbar.js
- client/routes.js
- server/api/cart.js
- server/api/order.js
- order history page complete with navbar link
-removed /:total from checkout route
-removed ALL instances of shipping address from checkout api and front-end, including all logic related to that.
> Orderhistory

- script/seed.js
- server/api/products.js
- Basically just updated the seed file to use the correct purchasingPrice
> Updating purchasingprice

- client/components/AllProducts.js
- client/components/NoPageFound.js
- client/components/Order.js
- client/components/ShoppingCart.js
- client/routes.js
- script/seed.js
- server/api/cart.js
- server/api/order.js
Got guest checkout working, updates stock as well
> Checkoutlogic

- client/components/SingleProduct.js
> updated price on isngleproduct page
